---
# Decisis-specific configuration

# Whether this project's Ansible playbooks should manage Docker on this host
manage_docker: true

# Docker Role variables
# Only used if `manage_docker: true` above.
# See https://github.com/geerlingguy/ansible-role-docker/blob/master/defaults/main.yml
# for available overrides.
docker_users:
  - "{{ ansible_user_id }}"

# Bot Identity
bot_nick: "Decisis"
bot_username: "decisis"
bot_realname: "Amicus Curiae"
bot_admin: "TedSki <email: tedski@efnetmoto.com>"
bot_owner: "TedSki"

# DCC/Telnet Port
dcc_port: &dcc_port 2020

# Docker compose environment variables
environment_variables:
  dcc_port: *dcc_port
  tz: "America/Los_Angeles"

# Runtime directories to create
runtime_dirs:
  - "bots/Decisis/data"
  - "bots/Decisis/data/seen"
  - "bots/Decisis/logs"

# Scripts to load (relative to container paths)
# (Scripts loaded from `scripts/` are Eggdrop-native and ship with the container)
bot_scripts:
  - "scripts/alltools.tcl"
  - "scripts/action.fix.tcl"
  - "scripts/dccwhois.tcl"
  - "scripts/userinfo.tcl"
  - "scripts/quotepong.tcl"
  - "scripts-shared/bseen1.4.2.tcl"
