---
# Pompone-specific configuration

# Whether this project's Ansible playbooks should manage Docker on this host
manage_docker: true

# Docker Role variables
# Only used if `manage_docker: true` above.
# See https://github.com/geerlingguy/ansible-role-docker/blob/master/defaults/main.yml
# for available overrides.
docker_users:
  - "{{ ansible_user_id }}"

# Bot Identity
bot_nick: "Pompone"
bot_username: "pompone"
bot_realname: "Motociclismo Paesano"
bot_admin: "TedSki <email: tedski@efnetmoto.com>"
bot_owner: "TedSki"

# DCC/Telnet Port
dcc_port: &dcc_port 2020

# Docker compose environment variables
environment_variables:
  dcc_port: *dcc_port
  stats_port: 8080  # Stats HTTP Port (nginx)
  cron_schedule: "{{ pisg_cron_schedule }}"
  tz: "America/Los_Angeles"

# Runtime directories to create
runtime_dirs:
  - "bots/Pompone/data"
  - "bots/Pompone/logs/bot"
  - "bots/Pompone/logs/channels"
  - "bots/Pompone/scripts"
  - "bots/Pompone/text"
  - "bots/Pompone/pisg-cache"
  - "bots/Pompone/pisg-config"
  - "bots/Pompone/html"

# Separate log directories for pisg processing
separate_log_dirs: true

# Scripts to load (relative to container paths)
# (Scripts loaded from `scripts/` are Eggdrop-native and ship with the container)
bot_scripts:
  - "scripts/alltools.tcl"
  - "scripts/action.fix.tcl"
  - "scripts/dccwhois.tcl"
  - "scripts/userinfo.tcl"
  - "scripts/quotepong.tcl"

# PISG Configuration
pisg_enabled: true
pisg_cron_schedule: "@hourly"  # Hourly
pisg_channels:
  - name: "#motorcycles"
    log_prefix: "motorcycles"
    format: "eggdrop"
    network: "Efnet"
    maintainer: "Pompone"
    output_file: "index.html"
